### ISSUE TITLE
Incompability with some interpolators

### ISSUE THREAD

**Issue by NoelleTGS** [Mrcubix/OTD.EnhancedOutputMode#4]
Hi, just wondering if this plugin has Linux support? Can't seem to get it to work, and I see this in the console tab so I'm not sure whether I'm doing anything wrong or it just isn't supported.

```
[Plugin:Info]	Plugin 'VoiDPlugins.OutputMode.VMultiAbsoluteMode' is not supported on Linux
[Plugin:Info]	Plugin 'OTD.EnhancedOutputMode.Output.EnhancedVMultiRelativeOutputMode' is not supported on Linux
[Plugin:Info]	Plugin 'OTD.EnhancedOutputMode.Output.EnhancedWindowsInkRelativeOutputMode' is not supported on Linux
[Plugin:Info]	Plugin 'OTD.EnhancedOutputMode.Output.EnhancedWindowsInkAbsoluteMode' is not supported on Linux
```

**Comment by Mrcubix** [comment]
As you can see, Windows Ink & Vmulti are only supported on windows.

On linux you don't need those, you can use Artist mode if you need pressure to draw for example.

> Can't seem to get it to work.

Which part? You should be able to switch the output mode ro the Enhanced Output Modes now that the plugin is installed.

I tried it in a Mint VM, an physical Mint install & on my raspberry pi to make sure it worked.

**Comment by NoelleTGS** [comment]
Sorry I should have been more clear, I'm unable to get the mouse to move with touch input. I've tried all the enhanced output modes, restarting the service, reinstalling the filter, nothing has worked. The tablet debugger shows touch is being detected and the blue light on my CTH-680 is coming on, so I don't think the tablet is the issue.

**Comment by NoelleTGS** [comment]
Oops sorry, I've figured out the issue. The plugin seems to be incompatible with the Temporal Resampler plugin. Disabling that plugin allows this to work.

**Comment by Mrcubix** [comment]
Since my output modes support touch, it's possible that these inputs interfere with interpolators, will try to look into fixes, but can't guarantee anything yet.
Will allow myself to edit the title just so i can track the issue.

**Comment by Mrcubix** [comment]
Found the issue, it turns out that Temporal Resampler blocks any types of inputs (including not positional) that it doesn't handle.
This not only breaks touch inputs, but any other kind of reports handled by other plugins, and is effectively a critical issue.

**Comment by Mrcubix** [comment]
Turns out that pre-transform interpolators are still first in the pipeline, meaning that touch inputs weren't converted into something that OTD filters can handle and send to the OS.
The workaround is to convert those touch inputs before anything else & hope nothing else breaks.
Other inputs types might still be blocked.
(And of course, this only happen in barely working 0.6.x)

Anyway, the update should be available in the plugin manager soon, in the meanwhile, you can download the latest release & install it from the plugin manager:

https://github.com/Mrcubix/OTD.EnhancedOutputMode/releases/tag/1.1.5-0.6.x

**Comment by Mrcubix** [comment]
Closing as it was fixed in a new update (they finally did it)
