### ISSUE TITLE
Enhanced Relative Mode Touch Sensitivity Doesnt Match Pen Sensitivity

### ISSUE THREAD

**Issue by xSamel-The-Camelx** [Mrcubix/OTD.EnhancedOutputMode#5]
When set to Enhanced Relative Mode the touch sensitivity is about 5x lower than what it should be.

I suspect the reason for it being something to do with the touch position reading in the tablet debugger going up to x=12439 y=8639 while the pen goes up to x=62200 y=43200

Changing settings for the Max X and Max Y have no effect on this mode

Everything seems to be working as intended for Enhanced Absolute Mode

Im using the Wacom PTH-860

**Comment by Mrcubix** [comment]
The more i experiment, the less likely it seem i will be able to achieve the result you're expecting.
Don't expect this come to be added by me at all at this point.

**Comment by xSamel-The-Camelx** [comment]
All good if its not possible.
All the projects you've worked on have made things possible I thought I wouldn't see for years or even never.


I'm very new to coding so I'm not sure how practical these are to implement but I have a few ideas.

1. Make it so its treated as a separate input/device. I know I can give it a custom sensitivity outside of OTD and make it work as desired.

2. Expose the sensitivity for the touch so it can be modified separately, even if the numbers aren't true to the actual px/mm.

3. Assume the physical size of both digitizes are the same and just multiply the pen sensitivity by the difference in resolution. 
Using my tablet and settings as an example: 
I use 40 px/mm for my x and y
divide pen x by touch x  62200/12439 = 5.00040196157
same for y 43200/8639 = 5.00057877069
use those numbers to modify the pen sensitivity
X: 40 x 5.00040196157 = 200.016078463
Y: 40 x 5.00057877069 = 200.023150828

**Comment by Mrcubix** [comment]
I wouldn't say it's not possible, it probably is, i just can't figure out the math yet.

James pointed out that maybe i could calculate a multiplier using both lpmm and use that as a multiplier for the touch transformation matrix.

Right now however users might be used to the existing behavior so instead i will opt for adding an extra setting.

As for the rest of your questions:

1. OTD doesn't really provide a way to acgieve that internally, and it would only work externally if touch inputs are sent on another endpoint, which is only the case for old bamboo tablets (CTH line).
2. That could be done, however as i've said, your cursor will be moving way slower than your pen, and you might have to increase sensitivity to around 8.00 or even 12.00, which doesn't feel exactly right.
3. Seems to be simillar or the same as what james mentionned, will give that a try this week-end or during a break as i'm currently spending most of my time reaching a job application quota.

**Comment by Mrcubix** [comment]
Give this build a try: https://github.com/Mrcubix/OTD.EnhancedOutputMode/actions/runs/11524106051#:~:text=Name,-Size

Also fixes a bug i thought i fixed where the cursor will teleport when switching finger

**Comment by xSamel-The-Camelx** [comment]
The toggle you speak of doesn't seem to exist, unless I'm misunderstanding where it's suppose to be.
![image](https://github.com/user-attachments/assets/f2a7e1dd-a817-4d21-96c4-83aa4ea2dcaa)

**Comment by Mrcubix** [comment]
What.

The CI should add provided a build with the correct changes, let me check.

**Comment by Mrcubix** [comment]
[OTD.EnhancedOutputMode-0.6.x.zip](https://github.com/user-attachments/files/17545411/OTD.EnhancedOutputMode-0.6.x.zip)

Should be the updated build for 0.6.x

**Comment by xSamel-The-Camelx** [comment]
Good news, the button exists.
Bad news, the button doesn't change anything. Even after tinkering with the Max X and Max Y settings.

I did try every other setting in Touch Settings and they all worked as intended.

**Comment by Mrcubix** [comment]
> Reset Time is confirmed very much so not working at all for touch input. Still works for pen input

Main issue is that touch inputs are sent at all time, even when not active, compared to pen inputs which are usually only sent when used.

I don't know if the new behavior make it better or worse.

> Bad news, the button doesn't change anything. Even after tinkering with the Max X and Max Y settings.

Odd, as it does something on my side, will test it on another device just to make sure.

> other than some minor buggyness of uninstalling the old ver and installing the ver you gave me

Known OTD issue, you usually have to just extract inside the plugin's folder instead, otherwise, it will some cache that doesn't exist, yet does magically.

**Comment by Mrcubix** [comment]
[OTD.EnhancedOutputMode-0.6.x.zip](https://github.com/user-attachments/files/17548568/OTD.EnhancedOutputMode-0.6.x.zip)

Turns out at some point i started using the property instead of the field that is correctly set, this should fix it, the result is the correct one now.

**Comment by Mrcubix** [comment]
Asked someone else to test the new build, seems like the behavior you requested works as intended, will still wait for your input before merging.

**Comment by xSamel-The-Camelx** [comment]
All testing I could do worked out wonderfully. more than accurate enough for my standards. 
Tested using math to figure out the exact sensitivity needed to make it across my monitor with one swipe across the tablet and it was perfect.

**Comment by Mrcubix** [comment]
Last thing would be, do you think the current behavior of it reseting when a new "primary" is detected is fine,
instead of having to configure a separate reset time for touch

**Comment by xSamel-The-Camelx** [comment]
I think its fine yea. If not potentially better than having reset time implemented.

Im running dwm on Gentoo. Trying to keep my setup minimal and would prefer to not have to permanently run something that requires a million dependencies, but I can also test on any/all of the potential solutions.

**Comment by Mrcubix** [comment]
Current status is available in #3, will upload a link there soon.

But anyway, this should be closed when i do some more checks & fixes.
